version: "3.8"

services:
  backend:
    build: ./apps/backend
    ports:
      - "4000:4000"
    env_file:
      - ./apps/backend/.env

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
