FROM node:20-alpine

WORKDIR /app

# Copy only frontend package files
COPY apps/frontend/package*.json ./apps/frontend/

# Install dependencies only for frontend
RUN npm install --prefix ./apps/frontend --production

# Copy frontend source code only
COPY apps/frontend ./apps/frontend

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "run", "dev", "--prefix", "apps/frontend"]
