FROM node:20-alpine

WORKDIR /app

# Copy only backend package files
COPY apps/backend/package*.json ./apps/backend/

# Install dependencies only for backend
RUN npm install --prefix ./apps/backend --production

# Copy backend source code only
COPY apps/backend ./apps/backend

ENV NODE_ENV=production
EXPOSE 4000

CMD ["npm", "start", "--prefix", "apps/backend"]
