name: Facelog CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Root Dependencies
        run: npm install

      - name: Build All Apps with Turbo
        run: npx turbo run build

      - name: Deploy to EC2 with PM2
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $SERVER_USER@$SERVER_IP << 'EOF'
            cd facelog
            git pull origin main

            npm install
            npx turbo run build

            cd apps/backend
            pm2 restart facelog-backend || pm2 start index.js --name facelog-backend

            cd ../frontend
            pm2 restart facelog-frontend || pm2 start "npm run start" --name facelog-frontend

            pm2 save
          EOF
