name: Build and Deploy to EC2 via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/facelog-backend -f apps/backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/facelog-backend

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/facelog-frontend -f apps/frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/facelog-frontend

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🛑 Killing any process using ports 3000 or 4000..."
            fuser -k 3000/tcp || true
            fuser -k 4000/tcp || true

            echo "🧼 Stopping/removing any existing containers..."
            docker stop frontend || true && docker rm frontend || true
            docker stop backend || true && docker rm backend || true

            echo "🧹 Cleaning up unused Docker images/layers..."
            docker system prune -af || true

            echo "📦 Pulling new images..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/facelog-frontend
            docker pull ${{ secrets.DOCKER_USERNAME }}/facelog-backend

            echo "🚀 Starting new backend container..."
            docker run -d --name backend -p 4000:4000 -e SUPABASE_URL="${{ secrets.SUPABASE_URL }}" -e SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}" ${{ secrets.DOCKER_USERNAME }}/facelog-backend

            echo "🚀 Starting new frontend container..."
            docker run -d --name frontend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/facelog-frontend
