name: Build and Deploy to EC2 via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/facelog-backend -f apps/backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/facelog-backend

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/facelog-frontend -f apps/frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/facelog-frontend

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Free port 3000 (frontend)
            frontend_pid=$(sudo lsof -t -i:3000 || true)
            if [ -n "$frontend_pid" ]; then
              echo "Port 3000 in use by PID $frontend_pid, killing it..."
              sudo kill -9 $frontend_pid
            fi

            # Free port 4000 (backend)
            backend_pid=$(sudo lsof -t -i:4000 || true)
            if [ -n "$backend_pid" ]; then
              echo "Port 4000 in use by PID $backend_pid, killing it..."
              sudo kill -9 $backend_pid
            fi

            # Stop and remove any existing containers
            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true

            # Optional: Clean up unused images/layers
            docker image prune -f


            # Run containers
            docker run -d --name backend -p 4000:4000 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" ${{ secrets.DOCKER_USERNAME }}/facelog-backend

            docker run -d --name frontend -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/facelog-frontend
